rwstudio=rws.getRobWorkStudio()
wc=rwstudio.getWorkCell(rwstudio)
world=wc.findFrame(wc,"WORLD")
tool=wc.findFrame(wc,"Tool.TCP")
fixture=wc.findFrame(wc,"Fixture_offset")
part1=wc.findFrame(wc,"Part1_OuterShell")
part2=wc.findFrame(wc,"Part2_InnerStructure")
part3=wc.findFrame(wc,"Part3_Thermoelement")
part4=wc.findFrame(wc,"Part4_Spring")
part5=wc.findFrame(wc,"Part5_Pin")
part6=wc.findFrame(wc,"Part6_ScrewPart")
part7=wc.findFrame(wc,"Part7_Nut")
part1A=wc.findFrame(wc,"Part1_OuterShell_Alternative_Collision_Model")
part2A=wc.findFrame(wc,"Part2_InnerStructure_Alternative_Collision_Model")

grasp1=wc.findFrame(wc,"Grasp_OuterShell")
grasp2=wc.findFrame(wc,"Grasp_InnerStructure")
grasp3=wc.findFrame(wc,"Grasp_Thermoelement")
grasp4=wc.findFrame(wc,"Grasp_Spring")
grasp5=wc.findFrame(wc,"Grasp_Pin")
grasp6=wc.findFrame(wc,"Grasp_ScrewPart")

assembly =wc.findFrame(wc,"Assembly")
assembly1=wc.findFrame(wc,"Assembly_OuterShell")
assembly2=wc.findFrame(wc,"Assembly_InnerStructure")
assembly3=wc.findFrame(wc,"Assembly_Thermoelement_Retracted")
assembly4=wc.findFrame(wc,"Assembly_Spring")
assembly5=wc.findFrame(wc,"Assembly_Pin")
assembly6=wc.findFrame(wc,"Assembly_ScrewPart")

assembly1r=wc.findFrame(wc,"Assembly_OuterShell_Retracted")
assembly2r=wc.findFrame(wc,"Assembly_InnerStructure_Retracted")
assembly3r=wc.findFrame(wc,"Assembly_Thermoelement_Retracted")
assembly4r=wc.findFrame(wc,"Assembly_Spring_Retracted")
assembly5r=wc.findFrame(wc,"Assembly_Pin_Retracted")
assembly6r=wc.findFrame(wc,"Assembly_ScrewPart_Retracted")

pick1=wc.findFrame(wc,"Pick_OuterShell_Obj")
pick2=wc.findFrame(wc,"Pick_InnerStructure_Obj")
pick6=wc.findFrame(wc,"Pick_ScrewPart_Obj")

state=wc.getDefaultState(wc)
part6.attachTo(part1,grasp1,state)
part6.attachTo(part1,pick1,state)
part6.attachTo(part2,pick2,state)
part6.attachTo(part6,pick6,state)

--part6.attachTo(part1A,assembly1,state)
--part6.attachTo(part2,assembly2r,state)




--part6.attachTo(part1,assembly1,state)
--part6.attachTo(part1,pick1,state)
--part6.attachTo(part2,assembly2,state)
--part6.attachTo(part3,assembly3,state)
--part6.attachTo(part4,assembly4,state)
--part6.attachTo(part5,assembly5,state)
--part6.attachTo(part6,assembly6,state)

rwstudio.setState(rwstudio,state)
